apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    name: http
  selector:
    app: mysql
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.5
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "111111"
        ports:
        - containerPort: 3306
          hostPort: 3306