apiVersion: v1
kind: Service
metadata:
  name: tomcatsvc
  labels:
    app: tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: tomcat
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: demo_image
        ports:
        - containerPort: 8080
          hostPort: 8080